//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardName {
            get {
                return ResourceManager.GetString("DashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string EditorsGroupTitle {
            get {
                return ResourceManager.GetString("EditorsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        public static string GoToTodayButton {
            get {
                return ResourceManager.GetString("GoToTodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu edited successfully!.
        /// </summary>
        public static string MealEditorMenuEditedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("MealEditorMenuEditedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new meal to the menu.
        /// </summary>
        public static string MenuEditorAddMealToMenuTitle {
            get {
                return ResourceManager.GetString("MenuEditorAddMealToMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to details.
        /// </summary>
        public static string MenuEditorBackToDetailsActionTitle {
            get {
                return ResourceManager.GetString("MenuEditorBackToDetailsActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu.
        /// </summary>
        public static string MenuEditorCreateMenuTitle {
            get {
                return ResourceManager.GetString("MenuEditorCreateMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menu.
        /// </summary>
        public static string MenuEditorDeleteMenuActionTitle {
            get {
                return ResourceManager.GetString("MenuEditorDeleteMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to change the meals&apos; order.
        /// </summary>
        public static string MenuEditorDragToReorderTitle {
            get {
                return ResourceManager.GetString("MenuEditorDragToReorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals planned for this day.
        /// </summary>
        public static string MenuEditorMealsPlannedTitle {
            get {
                return ResourceManager.GetString("MenuEditorMealsPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu created successfully!.
        /// </summary>
        public static string MenuEditorMenuCreatedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("MenuEditorMenuCreatedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of portions.
        /// </summary>
        public static string MenuEditorNumberOfServingsTitle {
            get {
                return ResourceManager.GetString("MenuEditorNumberOfServingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string MenuEditorSaveChangesButtonTitle {
            get {
                return ResourceManager.GetString("MenuEditorSaveChangesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for meal....
        /// </summary>
        public static string MenuEditorSearchForMealTitle {
            get {
                return ResourceManager.GetString("MenuEditorSearchForMealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one meal!.
        /// </summary>
        public static string MenuEditorValidationMealsError {
            get {
                return ResourceManager.GetString("MenuEditorValidationMealsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string MenuEditorWeekNameApplicationTitle {
            get {
                return ResourceManager.GetString("MenuEditorWeekNameApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string MenusGroupTitle {
            get {
                return ResourceManager.GetString("MenusGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new recipe.
        /// </summary>
        public static string RecipeCreateLinkTitle {
            get {
                return ResourceManager.GetString("RecipeCreateLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new recipe.
        /// </summary>
        public static string RecipeCreatorApplicationTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe +.
        /// </summary>
        public static string RecipeCreatorCreateRecipeButtonTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorCreateRecipeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ingredients.
        /// </summary>
        public static string RecipeCreatorIngredientsAddButtonTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientsAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved ingredient.
        /// </summary>
        public static string RecipeCreatorIngredientSavedIconTooltip {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientSavedIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string RecipeCreatorIngredientsQuantityTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientsQuantityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for ingredient....
        /// </summary>
        public static string RecipeCreatorIngredientsSearchTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientsSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string RecipeCreatorIngredientsSectionTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure units.
        /// </summary>
        public static string RecipeCreatorIngredientsUnitTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorIngredientsUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RecipeCreatorNameRequiredError {
            get {
                return ResourceManager.GetString("RecipeCreatorNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        public static string RecipeCreatorNameTextField {
            get {
                return ResourceManager.GetString("RecipeCreatorNameTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe added successfully!.
        /// </summary>
        public static string RecipeCreatorRecipeAddedConfirmation {
            get {
                return ResourceManager.GetString("RecipeCreatorRecipeAddedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add step.
        /// </summary>
        public static string RecipeCreatorRecipeStepsAddButtonTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorRecipeStepsAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string RecipeCreatorRecipeStepsInstructionTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorRecipeStepsInstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe steps.
        /// </summary>
        public static string RecipeCreatorRecipeStepsSectionTitle {
            get {
                return ResourceManager.GetString("RecipeCreatorRecipeStepsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of servings is required.
        /// </summary>
        public static string RecipeCreatorServingsRequiredError {
            get {
                return ResourceManager.GetString("RecipeCreatorServingsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of servings.
        /// </summary>
        public static string RecipeCreatorServingsTextField {
            get {
                return ResourceManager.GetString("RecipeCreatorServingsTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the ingredients and their units!.
        /// </summary>
        public static string RecipeCreatorValidationIngredientsError {
            get {
                return ResourceManager.GetString("RecipeCreatorValidationIngredientsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please name the recipe!.
        /// </summary>
        public static string RecipeCreatorValidationNameError {
            get {
                return ResourceManager.GetString("RecipeCreatorValidationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the steps!.
        /// </summary>
        public static string RecipeCreatorValidationStepsError {
            get {
                return ResourceManager.GetString("RecipeCreatorValidationStepsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string RecipeEditorApplicationTitle {
            get {
                return ResourceManager.GetString("RecipeEditorApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info saved!.
        /// </summary>
        public static string RecipeEditorBasicInfoSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorBasicInfoSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new recipe.
        /// </summary>
        public static string RecipeEditorCreateTitle {
            get {
                return ResourceManager.GetString("RecipeEditorCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient removed successfully.
        /// </summary>
        public static string RecipeEditorIngredientRemovedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient {0} saved.
        /// </summary>
        public static string RecipeEditorIngredientSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipeEditorNavigationTitle {
            get {
                return ResourceManager.GetString("RecipeEditorNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step saved successfully!.
        /// </summary>
        public static string RecipeEditorStepSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorStepSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All recipes.
        /// </summary>
        public static string RecipeListLinkTitle {
            get {
                return ResourceManager.GetString("RecipeListLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu.
        /// </summary>
        public static string ViewMenuCreateMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuCreateMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menu.
        /// </summary>
        public static string ViewMenuDeleteMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuDeleteMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit menu.
        /// </summary>
        public static string ViewMenuEditMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuEditMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (yields {1} portions).
        /// </summary>
        public static string ViewMenuMealListItemTitle {
            get {
                return ResourceManager.GetString("ViewMenuMealListItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu for {0}.
        /// </summary>
        public static string ViewMenuMenuForDayTitle {
            get {
                return ResourceManager.GetString("ViewMenuMenuForDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals for this day.
        /// </summary>
        public static string ViewMenuNoMealsLine1 {
            get {
                return ResourceManager.GetString("ViewMenuNoMealsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should eat something..
        /// </summary>
        public static string ViewMenuNoMealsLine2 {
            get {
                return ResourceManager.GetString("ViewMenuNoMealsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string ViewMenuWeekNameApplicationTitle {
            get {
                return ResourceManager.GetString("ViewMenuWeekNameApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe details.
        /// </summary>
        public static string ViewRecipeApplicationTitle {
            get {
                return ResourceManager.GetString("ViewRecipeApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all steps.
        /// </summary>
        public static string ViewRecipeCollapseAllStepsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeCollapseAllStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete recipe.
        /// </summary>
        public static string ViewRecipeDeleteRecipeActionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeDeleteRecipeActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string ViewRecipeEditRecipeActionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeEditRecipeActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all steps.
        /// </summary>
        public static string ViewRecipeExpandAllStepsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeExpandAllStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ViewRecipeGoBackButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeGoBackButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string ViewRecipeIngredientsSectionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeIngredientsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loeading....
        /// </summary>
        public static string ViewRecipeLoadingNameTitle {
            get {
                return ResourceManager.GetString("ViewRecipeLoadingNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals to display.
        /// </summary>
        public static string ViewRecipeNoRecipesToDisplayTitle {
            get {
                return ResourceManager.GetString("ViewRecipeNoRecipesToDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions.
        /// </summary>
        public static string ViewRecipeNumberOfPortionsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeNumberOfPortionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking steps.
        /// </summary>
        public static string ViewRecipeRecipeStepsSectionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeRecipeStepsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for recipe....
        /// </summary>
        public static string ViewRecipeSearchForRecipeTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSearchForRecipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients: {0} | Steps: {1} | Portions: {2}.
        /// </summary>
        public static string ViewRecipeShortSummaryTitle {
            get {
                return ResourceManager.GetString("ViewRecipeShortSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string ViewRecipeStepNameTitle {
            get {
                return ResourceManager.GetString("ViewRecipeStepNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to list.
        /// </summary>
        public static string ViewRecipeSwitchToListButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSwitchToListButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to tiles.
        /// </summary>
        public static string ViewRecipeSwitchToTilesButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSwitchToTilesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recipe.
        /// </summary>
        public static string ViewRecipeViewDetailsButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeViewDetailsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0} of {1}.
        /// </summary>
        public static string WeeklyMenuNavigationTitle {
            get {
                return ResourceManager.GetString("WeeklyMenuNavigationTitle", resourceCulture);
            }
        }
    }
}
