//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlanner.UI.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        public static string MainLayoutGoToTodayButtonTitle {
            get {
                return ResourceManager.GetString("MainLayoutGoToTodayButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu edited successfully!.
        /// </summary>
        public static string MealEditorMenuEditedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("MealEditorMenuEditedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new meal to the menu.
        /// </summary>
        public static string MenuEditorAddMealToMenuTitle {
            get {
                return ResourceManager.GetString("MenuEditorAddMealToMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to details.
        /// </summary>
        public static string MenuEditorBackToDetailsActionTitle {
            get {
                return ResourceManager.GetString("MenuEditorBackToDetailsActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu.
        /// </summary>
        public static string MenuEditorCreateMenuTitle {
            get {
                return ResourceManager.GetString("MenuEditorCreateMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menu.
        /// </summary>
        public static string MenuEditorDeleteMenuActionTitle {
            get {
                return ResourceManager.GetString("MenuEditorDeleteMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to change the meals&apos; order.
        /// </summary>
        public static string MenuEditorDragToReorderTitle {
            get {
                return ResourceManager.GetString("MenuEditorDragToReorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals planned for this day.
        /// </summary>
        public static string MenuEditorMealsPlannedTitle {
            get {
                return ResourceManager.GetString("MenuEditorMealsPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu created successfully!.
        /// </summary>
        public static string MenuEditorMenuCreatedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("MenuEditorMenuCreatedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu edited successfully!.
        /// </summary>
        public static string MenuEditorMenuEditedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("MenuEditorMenuEditedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of portions.
        /// </summary>
        public static string MenuEditorNumberOfServingsTitle {
            get {
                return ResourceManager.GetString("MenuEditorNumberOfServingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string MenuEditorSaveChangesButtonTitle {
            get {
                return ResourceManager.GetString("MenuEditorSaveChangesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for meal....
        /// </summary>
        public static string MenuEditorSearchForMealTitle {
            get {
                return ResourceManager.GetString("MenuEditorSearchForMealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one meal!.
        /// </summary>
        public static string MenuEditorValidationMealsError {
            get {
                return ResourceManager.GetString("MenuEditorValidationMealsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string MenuEditorWeekNameApplicationTitle {
            get {
                return ResourceManager.GetString("MenuEditorWeekNameApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string NavMenuDashboardName {
            get {
                return ResourceManager.GetString("NavMenuDashboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string NavMenuEditorsGroupTitle {
            get {
                return ResourceManager.GetString("NavMenuEditorsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string NavMenuMenusGroupTitle {
            get {
                return ResourceManager.GetString("NavMenuMenusGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe editor.
        /// </summary>
        public static string RecipeEditor {
            get {
                return ResourceManager.GetString("RecipeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new recipe.
        /// </summary>
        public static string RecipeEditorApplicationTitle {
            get {
                return ResourceManager.GetString("RecipeEditorApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info saved!.
        /// </summary>
        public static string RecipeEditorBasicInfoSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorBasicInfoSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe +.
        /// </summary>
        public static string RecipeEditorCreateRecipeButtonTitle {
            get {
                return ResourceManager.GetString("RecipeEditorCreateRecipeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new recipe.
        /// </summary>
        public static string RecipeEditorCreateTitle {
            get {
                return ResourceManager.GetString("RecipeEditorCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string RecipeEditorEditApplicationTitle {
            get {
                return ResourceManager.GetString("RecipeEditorEditApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient removed successfully.
        /// </summary>
        public static string RecipeEditorIngredientRemovedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ingredients.
        /// </summary>
        public static string RecipeEditorIngredientsAddButtonTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientsAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved ingredient.
        /// </summary>
        public static string RecipeEditorIngredientSavedIconTooltip {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientSavedIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient {0} saved.
        /// </summary>
        public static string RecipeEditorIngredientSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string RecipeEditorIngredientsQuantityTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientsQuantityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for ingredient....
        /// </summary>
        public static string RecipeEditorIngredientsSearchTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientsSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string RecipeEditorIngredientsSectionTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure units.
        /// </summary>
        public static string RecipeEditorIngredientsUnitTitle {
            get {
                return ResourceManager.GetString("RecipeEditorIngredientsUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RecipeEditorNameRequiredError {
            get {
                return ResourceManager.GetString("RecipeEditorNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe name.
        /// </summary>
        public static string RecipeEditorNameTextField {
            get {
                return ResourceManager.GetString("RecipeEditorNameTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new recipe.
        /// </summary>
        public static string RecipeEditorNavigationCreateLinkTitle {
            get {
                return ResourceManager.GetString("RecipeEditorNavigationCreateLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All recipes.
        /// </summary>
        public static string RecipeEditorNavigationListLinkTitle {
            get {
                return ResourceManager.GetString("RecipeEditorNavigationListLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipeEditorNavigationTitle {
            get {
                return ResourceManager.GetString("RecipeEditorNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial preparation removed.
        /// </summary>
        public static string RecipeEditorPreparationRemovedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorPreparationRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial preparations details saved.
        /// </summary>
        public static string RecipeEditorPreparationSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorPreparationSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe added successfully!.
        /// </summary>
        public static string RecipeEditorRecipeAddedConfirmation {
            get {
                return ResourceManager.GetString("RecipeEditorRecipeAddedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add step.
        /// </summary>
        public static string RecipeEditorRecipeStepsAddButtonTitle {
            get {
                return ResourceManager.GetString("RecipeEditorRecipeStepsAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string RecipeEditorRecipeStepsInstructionTitle {
            get {
                return ResourceManager.GetString("RecipeEditorRecipeStepsInstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe steps.
        /// </summary>
        public static string RecipeEditorRecipeStepsSectionTitle {
            get {
                return ResourceManager.GetString("RecipeEditorRecipeStepsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of servings is required.
        /// </summary>
        public static string RecipeEditorServingsRequiredError {
            get {
                return ResourceManager.GetString("RecipeEditorServingsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of servings.
        /// </summary>
        public static string RecipeEditorServingsTextField {
            get {
                return ResourceManager.GetString("RecipeEditorServingsTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step saved successfully!.
        /// </summary>
        public static string RecipeEditorStepSavedTitle {
            get {
                return ResourceManager.GetString("RecipeEditorStepSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the ingredients and their units!.
        /// </summary>
        public static string RecipeEditorValidationIngredientsError {
            get {
                return ResourceManager.GetString("RecipeEditorValidationIngredientsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please name the recipe!.
        /// </summary>
        public static string RecipeEditorValidationNameError {
            get {
                return ResourceManager.GetString("RecipeEditorValidationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the steps!.
        /// </summary>
        public static string RecipeEditorValidationStepsError {
            get {
                return ResourceManager.GetString("RecipeEditorValidationStepsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create menu.
        /// </summary>
        public static string ViewMenuCreateMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuCreateMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menu.
        /// </summary>
        public static string ViewMenuDeleteMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuDeleteMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit menu.
        /// </summary>
        public static string ViewMenuEditMenuActionTitle {
            get {
                return ResourceManager.GetString("ViewMenuEditMenuActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (yields {1} portions).
        /// </summary>
        public static string ViewMenuMealListItemTitle {
            get {
                return ResourceManager.GetString("ViewMenuMealListItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu for {0}.
        /// </summary>
        public static string ViewMenuMenuForDayTitle {
            get {
                return ResourceManager.GetString("ViewMenuMenuForDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals for this day.
        /// </summary>
        public static string ViewMenuNoMealsLine1 {
            get {
                return ResourceManager.GetString("ViewMenuNoMealsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should eat something..
        /// </summary>
        public static string ViewMenuNoMealsLine2 {
            get {
                return ResourceManager.GetString("ViewMenuNoMealsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string ViewMenuWeekNameApplicationTitle {
            get {
                return ResourceManager.GetString("ViewMenuWeekNameApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe details.
        /// </summary>
        public static string ViewRecipeApplicationTitle {
            get {
                return ResourceManager.GetString("ViewRecipeApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all steps.
        /// </summary>
        public static string ViewRecipeCollapseAllStepsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeCollapseAllStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete recipe.
        /// </summary>
        public static string ViewRecipeDeleteRecipeActionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeDeleteRecipeActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string ViewRecipeEditRecipeActionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeEditRecipeActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all steps.
        /// </summary>
        public static string ViewRecipeExpandAllStepsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeExpandAllStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ViewRecipeGoBackButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeGoBackButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string ViewRecipeIngredientsSectionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeIngredientsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahead of time prep.: {0} day(s).
        /// </summary>
        public static string ViewRecipeLeadDaysTitle {
            get {
                return ResourceManager.GetString("ViewRecipeLeadDaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loeading....
        /// </summary>
        public static string ViewRecipeLoadingNameTitle {
            get {
                return ResourceManager.GetString("ViewRecipeLoadingNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meals to display.
        /// </summary>
        public static string ViewRecipeNoRecipesToDisplayTitle {
            get {
                return ResourceManager.GetString("ViewRecipeNoRecipesToDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions.
        /// </summary>
        public static string ViewRecipeNumberOfPortionsTitle {
            get {
                return ResourceManager.GetString("ViewRecipeNumberOfPortionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string ViewRecipeOptionalTitle {
            get {
                return ResourceManager.GetString("ViewRecipeOptionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial preparations.
        /// </summary>
        public static string ViewRecipePreparationsSectionTitle {
            get {
                return ResourceManager.GetString("ViewRecipePreparationsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking steps.
        /// </summary>
        public static string ViewRecipeRecipeStepsSectionTitle {
            get {
                return ResourceManager.GetString("ViewRecipeRecipeStepsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string ViewRecipeRequiredTitle {
            get {
                return ResourceManager.GetString("ViewRecipeRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for recipe....
        /// </summary>
        public static string ViewRecipeSearchForRecipeTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSearchForRecipeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients: {0} | Steps: {1} | Portions: {2}.
        /// </summary>
        public static string ViewRecipeShortSummaryTitle {
            get {
                return ResourceManager.GetString("ViewRecipeShortSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string ViewRecipeStepNameTitle {
            get {
                return ResourceManager.GetString("ViewRecipeStepNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to list.
        /// </summary>
        public static string ViewRecipeSwitchToListButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSwitchToListButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to tiles.
        /// </summary>
        public static string ViewRecipeSwitchToTilesButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeSwitchToTilesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recipe.
        /// </summary>
        public static string ViewRecipeViewDetailsButtonTitle {
            get {
                return ResourceManager.GetString("ViewRecipeViewDetailsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week {0} of {1}.
        /// </summary>
        public static string WeeklyMenuNavigationTitle {
            get {
                return ResourceManager.GetString("WeeklyMenuNavigationTitle", resourceCulture);
            }
        }
    }
}
