<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <None Remove=".gitignore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MealPlanner.Client\MealPlanner.Client.csproj" />
      <ProjectReference Include="..\MealPlanner.Services\MealPlanner.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.7.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Translations.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Translations.Designer.cs</LastGenOutput>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Translations.pl.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Translations.pl.Designer.cs</LastGenOutput>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Translations.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Translations.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
