using MealPlanner.Domain.Ingredients;

namespace MealPlanner.Persistence.Seeders;

internal static partial class InitialData
{
    public static Ingredient[] Ingredients() =>
    [
        Ingredient.Create("Bułka", [MeasureUnit.Piece]),
        Ingredient.Create("Chleb", [MeasureUnit.Piece]),
        Ingredient.Create("Wrapy", [MeasureUnit.Piece, MeasureUnit.Package]),
        
        Ingredient.Create("Parówki Dolina Dobra", [MeasureUnit.Piece, MeasureUnit.Package]),
        Ingredient.Create("Kiełbasa Grillowa z karkówki Dolina Dobra", [MeasureUnit.Package, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Kiełbasa biała", [MeasureUnit.Package, MeasureUnit.Kilogram, MeasureUnit.Gram]),
        Ingredient.Create("Gryzzzale", [MeasureUnit.Package]),
        Ingredient.Create("Kabanosy", [MeasureUnit.Package]),
        Ingredient.Create("Szynka Dojrzewająca", [MeasureUnit.Package, MeasureUnit.Gram]),
        Ingredient.Create("Fuet", [MeasureUnit.Package]),
        Ingredient.Create("Boczek Lardons", [MeasureUnit.Gram]),
        Ingredient.Create("Boczek w plastrach Sokołów", [MeasureUnit.Package]),
        
        Ingredient.Create("Feta", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Ser na grilla", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Parmezan", [MeasureUnit.Gram, MeasureUnit.Piece]),
        
        Ingredient.Create("Mozzarella twarda", [MeasureUnit.Gram]),
        Ingredient.Create("Mozzarella kulka", [MeasureUnit.Piece]),
        Ingredient.Create("Mozzarella wędzona", [MeasureUnit.Piece]),
        Ingredient.Create("Mozzarella Mini", [MeasureUnit.Package]),
        
        Ingredient.Create("Ser żółty w plastrach, zwykły", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Ser żółty w plastrach, wędzony", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Ser żółty w plastrach, dojrzewający", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Mimolette", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Cheddar (kostka)", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Cheddar (tarty)", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Camembert", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Ser z przerostem pleśni", [MeasureUnit.Gram, MeasureUnit.Piece]),
        
        Ingredient.Create("Cytryna", [MeasureUnit.Piece]),
        Ingredient.Create("Limonka", [MeasureUnit.Piece]),
        Ingredient.Create("Gruszka", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Awokado", [MeasureUnit.Piece]),
        Ingredient.Create("Ananas", [MeasureUnit.Piece]),
        Ingredient.Create("Cebula żółta, mała", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cebula żółta, średnia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cebula żółta, duża", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cebula czerwona, mała", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cebula czerwona, średnia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cebula czerwona, duża", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Szalotka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Ząbki czosnku", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Czosnek (główka)", [MeasureUnit.Piece]),
        Ingredient.Create("Włoszczyzna na rosół", [MeasureUnit.Package]),
        Ingredient.Create("Marchew", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pietruszka (korzeń)", [MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Seler", [MeasureUnit.Gram, MeasureUnit.Piece]),
        
        Ingredient.Create("Papryka czerwona, mała", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka czerwona, średnia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka czerwona, duża", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka żółta, mała", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka żółta, średnia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka żółta, duża", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka zielona, mała", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka zielona, średnia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryka zielona, duża", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Papryczki na grilla", [MeasureUnit.Package]),
        Ingredient.Create("Jalapeno, świeże", [MeasureUnit.Package, MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ostra papryczka", [MeasureUnit.Package, MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek krótki, mały", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek krótki, średni", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek krótki, duży", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek długi, mały", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek długi, średni", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Ogórek długi, duży", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Cukinia", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Kukurydza", [MeasureUnit.Piece, MeasureUnit.Gram]),
        
        Ingredient.Create("Pomidor zwykły, mały", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidor zwykły, duży", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidor zwykły, średni", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidor malinowy, mały", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidor malinowy, duży", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidor malinowy, średni", [MeasureUnit.Kilogram, MeasureUnit.Gram, MeasureUnit.Piece]),
        Ingredient.Create("Pomidorki cherry", [MeasureUnit.Gram, MeasureUnit.Piece, MeasureUnit.Package]),
        Ingredient.Create("Pomidorki mini San Marzano", [MeasureUnit.Gram, MeasureUnit.Piece, MeasureUnit.Package]),
        
        Ingredient.Create("Ziemniaki, małe", [MeasureUnit.Gram, MeasureUnit.Piece, MeasureUnit.Package]),
        Ingredient.Create("Ziemniaki, średnie", [MeasureUnit.Gram, MeasureUnit.Piece, MeasureUnit.Package]),
        Ingredient.Create("Ziemniaki, duże", [MeasureUnit.Gram, MeasureUnit.Piece, MeasureUnit.Package]),

        Ingredient.Create("Sezam biały (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Sezam czarny (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Płatki migdałów", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Orzechy włoskie", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        
        Ingredient.Create("Bazylia (krzak)", [MeasureUnit.Piece]),
        Ingredient.Create("Oregano (krzak)", [MeasureUnit.Piece]),
        Ingredient.Create("Mięta (krzak)", [MeasureUnit.Piece]),
        Ingredient.Create("Kolendra (krzak)", [MeasureUnit.Piece]),
        Ingredient.Create("Rozmaryn (krzak)", [MeasureUnit.Piece]),
        Ingredient.Create("Szczypiorek (pęczek)", [MeasureUnit.Piece]),
        Ingredient.Create("Dymka (pęczek)", [MeasureUnit.Piece]),
        Ingredient.Create("Rzodkiewka", [MeasureUnit.Piece]),
        Ingredient.Create("Pieczarki", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Pieczarki Portobello", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Sałata masłowa", [MeasureUnit.Piece]),
        Ingredient.Create("Sałata rzymska", [MeasureUnit.Piece]),
        Ingredient.Create("Sałata lodowa", [MeasureUnit.Piece]),
        Ingredient.Create("Rukola", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Szpinak świeży", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Roszponka", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Miks Sałat", [MeasureUnit.Piece, MeasureUnit.Gram]),
        Ingredient.Create("Kiełki", [MeasureUnit.Package]),
        
        Ingredient.Create("Łosoś wędzony", [MeasureUnit.Package, MeasureUnit.Gram]),
        Ingredient.Create("Łosoś świeży", [MeasureUnit.Package, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Sos sojowy jasny", [MeasureUnit.Package, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Sos sojowy ciemny", [MeasureUnit.Package, MeasureUnit.Teaspoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Olej sezamowy prażony", [MeasureUnit.Package, MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Olej sezamowy zwykły", [MeasureUnit.Package, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Ryż do sushi", [MeasureUnit.Package, MeasureUnit.Gram, MeasureUnit.Milliliter]),
        Ingredient.Create("Ocet ryżowy", [MeasureUnit.Package, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Saszetka do woka", [MeasureUnit.Package]),
        Ingredient.Create("Warzywa do woka", [MeasureUnit.Package]),
        Ingredient.Create("Chilli Crisp", [MeasureUnit.Teaspoon, MeasureUnit.Tablespoon]),
        Ingredient.Create("Marynowane Jalapeno", [MeasureUnit.Piece]),
        
        Ingredient.Create("Mała Śmietana 12%", [MeasureUnit.Package, MeasureUnit.Tablespoon]),
        Ingredient.Create("Jogurt grecki", [MeasureUnit.Package, MeasureUnit.Gram, MeasureUnit.Tablespoon]),
        Ingredient.Create("Jogurt naturalny", [MeasureUnit.Package, MeasureUnit.Gram, MeasureUnit.Tablespoon]),
        Ingredient.Create("Śmietanka Zott 30%", [MeasureUnit.Package, MeasureUnit.Milliliter]),
        Ingredient.Create("Klinek", [MeasureUnit.Package]),
        Ingredient.Create("Philadelphia", [MeasureUnit.Package]),
        Ingredient.Create("Jajka L", [MeasureUnit.Piece]),
        Ingredient.Create("Mleko skondensowane w tubce", [MeasureUnit.Piece]),
        Ingredient.Create("Mleko", [MeasureUnit.Bottle, MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Tablespoon]),
        Ingredient.Create("Masło", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Tablespoon]),
        
        Ingredient.Create("Kalmary mrożone", [MeasureUnit.Package]),
        Ingredient.Create("Szpinak mrożony (liście)", [MeasureUnit.Package, MeasureUnit.Gram]),
        Ingredient.Create("Szpinak mrożony (rozdrobniony)", [MeasureUnit.Package, MeasureUnit.Gram]),
        
        Ingredient.Create("Frytki", [MeasureUnit.Package, MeasureUnit.Gram]),
        Ingredient.Create("Woda witaminowa", [MeasureUnit.Milliliter, MeasureUnit.Liter]),
        Ingredient.Create("Woda mineralna", [MeasureUnit.Milliliter, MeasureUnit.Liter]),
        Ingredient.Create("Woda źródlana", [MeasureUnit.Milliliter, MeasureUnit.Liter]),
        Ingredient.Create("Coca-Cola (Zero)", [MeasureUnit.Milliliter, MeasureUnit.Liter]),
        Ingredient.Create("Coca-Cola (Zwykła)", [MeasureUnit.Milliliter, MeasureUnit.Liter]),
        
        Ingredient.Create("Piwo", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino czerwone, wytrawne", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino czerwone, półwytrawne", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino czerwone, półsłodkie", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino czerwone, słodkie", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino białe, wytrawne", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino białe, półwytrawne", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino białe, półsłodkie", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino białe, słodkie", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Wino Rose", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Jagermeister", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Whiskey Irlandzka", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        Ingredient.Create("Whiskey Szkocka", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        
        Ingredient.Create("Sok jabłkowy NFC", [MeasureUnit.Milliliter, MeasureUnit.Liter, MeasureUnit.Bottle]),
        
        Ingredient.Create("Czekolada gorzka 80%", [MeasureUnit.Gram, MeasureUnit.Package]),
        
        Ingredient.Create("Ciastka Lotus", [MeasureUnit.Gram, MeasureUnit.Package]),
        
        Ingredient.Create("Spaghetti", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Wstążki bio", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Kokardki", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Rurki", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Krajanka rosołowa", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Pomidory w puszce, obrane, całe", [MeasureUnit.Can]),
        Ingredient.Create("Pomidory w puszce, obrane, kawałki", [MeasureUnit.Can]),
        Ingredient.Create("Koncentrat pomidorowy", [MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Passata", [MeasureUnit.Milliliter, MeasureUnit.Gram]),
        
        Ingredient.Create("Oliwki zielone", [MeasureUnit.Gram, MeasureUnit.Tablespoon]),
        Ingredient.Create("Oliwki czarne", [MeasureUnit.Gram, MeasureUnit.Tablespoon]),
        Ingredient.Create("Ogórki kiszone", [MeasureUnit.Gram, MeasureUnit.Piece]),
        
        Ingredient.Create("Olej", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Oliwa z oliwek EE", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Ocet jabłkowy", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Ocet z białego wina", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Ocet z czerwonego wina", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Ocet balsamiczny", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Sok z cytryny", [MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        Ingredient.Create("Sok z limonki", [MeasureUnit.Tablespoon, MeasureUnit.Milliliter]),
        
        Ingredient.Create("Ryż basmati (naturalny)", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Ryż basmati (łuskany)", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Ryż brązowy", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Ryż parboiled", [MeasureUnit.Gram, MeasureUnit.Package]),
        Ingredient.Create("Kuskus", [MeasureUnit.Gram, MeasureUnit.Package]),
        
        Ingredient.Create("Sól", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Pieprz kolorowy, ziarnisty", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Pieprz czarny, ziarnisty", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Pieprz biały", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Gyros (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Kurczak Złocisty (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Bazylia (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Oregano (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Gorczyca (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Kmin rzymski (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Czarnuszka (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Czosnek granulowany (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Cebula suszona (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Ziele angielskie (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Liść laurowy (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Papryka słodka (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Papryka ostra (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Papryka wędzona (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Sumak (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Tymianek (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Rozmaryn (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Cynamon (laska)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Cynamon (w proszku)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Przyprawa do ryb", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Grill Karkówka (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Grill Warzywa (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Przyprawa do frytek", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        Ingredient.Create("Zioła Prowansalskie (przyprawa)", [MeasureUnit.Pinch, MeasureUnit.Teaspoon, MeasureUnit.Tablespoon, MeasureUnit.Gram]),
        
        Ingredient.Create("Ketchup", [MeasureUnit.Gram, MeasureUnit.Tablespoon, MeasureUnit.Teaspoon]),
        Ingredient.Create("Majonez", [MeasureUnit.Gram, MeasureUnit.Tablespoon, MeasureUnit.Teaspoon]),
        Ingredient.Create("Musztarda francuska", [MeasureUnit.Gram, MeasureUnit.Tablespoon, MeasureUnit.Teaspoon]),
        Ingredient.Create("Musztarda dijon", [MeasureUnit.Gram, MeasureUnit.Tablespoon, MeasureUnit.Teaspoon]),
        
        Ingredient.Create("Pierś z kurczaka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Pałki z kurczaka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Ćwiartka z kurczaka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Schab", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Karkówka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Żeberka", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Polędwica wieprzowa", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Mięso mielone wieprzowe", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Łopatka wieprzowa", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Polędwica wołowa", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Stek z antrykotu", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Stek z rostbefu", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Mięso mielone wołowe", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Łopatka wołowa", [MeasureUnit.Piece, MeasureUnit.Gram, MeasureUnit.Kilogram]),
        Ingredient.Create("Szynka", [MeasureUnit.Gram]),
    ];
}